# Generated by Django 4.0 on 2022-04-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_alter_hobby_description_alter_hobby_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
        ),
    ]
