# Generated by Django 4.0 on 2022-04-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('username', models.CharField(max_length=150, verbose_name='Логин')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=254, verbose_name='Почта')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('gender', models.CharField(max_length=100, verbose_name='Пол')),
            ],
        ),
    ]
