# Generated by Django 4.0 on 2022-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0004_hobby_category'),
        ('users', '0004_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(to='hobbies.Hobby', verbose_name='Увлечения'),
        ),
    ]
