# Generated by Django 4.0 on 2022-04-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('address', models.CharField(max_length=2048)),
                ('date', models.CharField(max_length=100)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.hobby')),
            ],
        ),
    ]
