# Generated by Django 4.0 on 2022-04-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=2048, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2048, verbose_name='Описание'),
        ),
    ]
