# Generated by Django 4.0 on 2022-04-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_alter_hobby_description_alter_hobby_name'),
        ('events', '0003_alter_event_address_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.hobby', verbose_name='Тема'),
        ),
    ]
