# Generated by Django 4.0 on 2022-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_email_remove_profile_first_name_and_more'),
        ('events', '0004_alter_event_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator_name',
            field=models.CharField(default='', max_length=128, verbose_name='Создатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='users.Profile', verbose_name='Участники'),
        ),
    ]
