# Generated by Django 4.0.3 on 2022-04-02 22:11

from django.db import migrations, models
import django_admin_geomap


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
